apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-backend-deployment
  labels:
    app: crypto-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-backend
  template:
    metadata:
      labels:
        app: crypto-backend
    spec:
      containers:
        - name: crypto-backend
          image: razlevio/crypto-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: UPSTASH_REDIS_REST_URL
              value: 'https://keen-goblin-32497.upstash.io'
            - name: UPSTASH_REDIS_REST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: crypto-redis-secret
                  key: UPSTASH_REDIS_REST_TOKEN
            - name: COINLAYER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto-coinlayer-secret
                  key: COINLAYER_API_KEY
